name: 'Continuous Delivery'

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: 'challengelatam-435501'
        export_default_credentials: true

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/challengelatam-435501/prediction-api . 

    - name: Run Tests in Docker  
      run: |
        docker run --rm gcr.io/challengelatam-435501/prediction-api make model-test  
        docker run --rm gcr.io/challengelatam-435501/prediction-api make api-test 

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/challengelatam-435501/prediction-api 

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy delay-prediction-api --image gcr.io/challengelatam-435501/prediction-api --platform managed --region southamerica-west1 --allow-unauthenticated