name: 'Continuous Integration'

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code  
      uses: actions/checkout@v3 

    - name: Set up Python  
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9' 

    - name: Install dependencies  
      run: |
        pip install -r requirements.txt

    - name: Run tests for model and API  
      run: |
        make model-test  
        make api-test    

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true